### ISSUE TITLE
Finder triggers telescope buffers for some reason

### ISSUE THREAD

**Issue by vitarb** [nvimdev/lspsaga.nvim#1070] opened 2023-05-13 20:17 UTC
### Describe the bug

I have default configuration for both [telescope](https://github.com/vitarb/nvim-config/blob/saga/lua/plugins/setup/telescope.lua) and [lspsaga](https://github.com/vitarb/nvim-config/blob/saga/lua/plugins/setup/lspsaga.lua). Full config available here: https://github.com/vitarb/nvim-config/tree/saga

### Steps to reproduce

When I use lsp_finder or other saga commands like incoming/outgoing calls, telescope "buffers" window gets opened in the background:
![2023-05-13_13-00](https://github.com/nvimdev/lspsaga.nvim/assets/1311694/bb960767-74ff-4a46-892d-53e134009210)

I have no shortcut conflicts, and tried remapping saga commands to different key combinations, but still seeing same issue.

### Expected behavior

No telescope window should be open on reference search.

### Neovim version (nvim -v)

v0.9.0

### lspsaga commit

latest

### Terminal name/version

alacritty

**Comment by glepnir** [comment] 2023-05-14 01:01
sry can't reproduce with it please try a min config .

**Comment by JasonPanosso** [comment] 2023-05-23 17:48
Mindblowingly this probably is caused by a keymap conflict.

@vitarb in your Telescope config you are setting the `Telescope buffers` keymap here: 
`map('n', '<C-e>', builtin.buffers, "Buffers")`

I was doing something similar with `<C-e>`, however I was opening a popup window for a different plugin(harpoon).

After spending a bit digging through lspsaga, I found what I believe is causing this bug:

`lua/lspsaga/definition.lua` line 178:
```lua
    local keycode = api.nvim_replace_termcodes('5<C-e>', true, false, true)
```
`callhierarchy.lua` line 366:
```lua
    local keycode = api.nvim_replace_termcodes('5<C-e>', true, false, true)
```
`finder.lua` line 407:
```lua
    local keycode = api.nvim_replace_termcodes('6<C-e>', true, false, true)

```

All of these are within the functions that handle the rendering/creation of the popup windows. I believe `<C-e>` is being used to center the popup window, but I'm not completely sure tbh. 

@glepnir is it realistic to change how this is being done? I'd like to keep using `<C-e>` as my keybind for the other plugin that I am using, however for the time being I've remapped it to work around this bug.

Appreciate any help, and thanks for the awesome plugin!

**Comment by glepnir** [comment] 2023-05-24 00:50
Currently use 5 <C-e> to push the screen to get enough room to show the window. This has similar behavior to vscode. But I overlooked that the keys might be reset. So I should try to find an api or write a function to push the window

**Comment by nikbrunner** [comment] 2023-06-03 17:51
I stumpled across the the same issue. For me its opening Neo-tree buffers, which I also binded to `<C-e>` in Normal Mode. When I trigger `<cmd>Lspsaga lsp_finder<CR>` it opens the Lspsaga Window and the Neotree window.

![image](https://github.com/nvimdev/lspsaga.nvim/assets/46924729/fcfaec3f-5db8-4017-bb8e-ea56edf8d26c)

**Comment by glepnir** [comment] 2023-06-04 01:05
like a said looking for a scroll api to do this and recently bug fix is in next version. because next version rewrite all .

**Closed** 2023-07-09 12:06 UTC
Labels: bug
